services:
  gateway:
    image: monamimamimamo/gateway:1.4
    ports:
      - "8082:8082"
    environment:
      - server.ssl.key-store=classpath:keystore.jks
      - server.ssl.key-store-type=JKS
      - server.ssl.key-store-password=aA258007195

  kurento-group-call:
    image: monamimamimamo/kurento-group-call:1.3
    depends_on:
      - gateway
    ports:
      - "8443:8443"
    environment:
      - server.ssl.key-store=classpath:keystore.jks
      - server.ssl.key-store-type=JKS
      - server.ssl.key-store-password=aA258007195

  p2p-signaling:
    image: monamimamimamo/p2p-signaling:1.0
    depends_on:
      - gateway
    ports:
      - "9000:9000"
    environment:
      - server.ssl.key-store=classpath:keystore.jks
      - server.ssl.key-store-type=JKS
      - server.ssl.key-store-password=aA258007195

  p2p-chat:
    image: monamimamimamo/p2p_chat:1.0
    depends_on:
      - gateway
      - db
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/p2p_chat

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: p2p_chat
    ports:
      - "5432:5432"

volumes:
  db_data: