server:
  port: 8082
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: aA258007195
    key-store-type: JKS

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: groupCall_route
          uri: wss://kurento-group-call:8443
          predicates:
            - Path=/groupcall
        - id: p2p_signaling_route
          uri: wss://p2p-signaling:9000
          predicates:
            - Path=/p2p
      httpclient:
        ssl:
          useInsecureTrustManager: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  pattern: console=%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n

management:
  endpoints:
    web:
      exposure:
        include: info\\\