server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  pattern: console=%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n

management:
  endpoints:
    web:
      exposure:
        include: info\\\
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka