server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: p2p_chat_http_route
          uri: https://p2p-chat:9003
          predicates:
            - Path=/chat/**
        - id: swagger_ui_route
          uri: http://identity.webapi:8080
          predicates:
            - Path=/swagger/**
            - Path=/api/**
        - id: groupCall_route
          uri: wss://kurento-group-call:8443
          predicates:
            - Path=/groupcall
        - id: p2p_signaling_route
          uri: https://p2p-signaling:9002
          predicates:
            - Path=/signaling/**
        - id: friendship_route
          uri: https://friendship-manager:9004
          predicates:
            - Path=/friendship/**
      httpclient:
        ssl:
          useInsecureTrustManager: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  pattern: console=%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n

management:
  endpoints:
    web:
      exposure:
        include: info\\\