spring:
  application:
    name: p2p-chat
  datasource:
    url: jdbc:postgresql://localhost:5432/p2p_chat
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: FBF0E5C5-056A-4DE9-A9B4-CAC04513C5D8

server:
  port: 9003
