spring:
  application:
    name: p2p-chat
  datasource:
    url: jdbc:postgresql://localhost:5432/p2p_chat
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: org.example.domain.KafkaFriendshipMessage

server:
  port: 9003