spring:
  application:
    name: p2p-chat
  datasource:
    url: jdbc:postgresql://localhost:5432/p2p_chat
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092


server:
  port: 9003
